# Generated by Django 2.1.5 on 2020-07-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
