# Generated by Django 2.1.5 on 2020-07-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0002_gatos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatos',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
