# Generated by Django 2.1.5 on 2020-07-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adopciones', '0003_gatos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=70)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Gatos',
            new_name='Mascotas',
        ),
    ]
